title: Beginner Baker's Guide
description: This is a guide for beginner bakers.
theme: just-the-docs

url: https://IzatheWriter.github.io/BeginnerBakersGuide

aux_links:
  Template Repository: https://github.com/IzatheWriter/BeginnerBakersGuide
